//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbanhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int MaBinhLuan { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> MaTV { get; set; }
        public Nullable<int> MaSP { get; set; }
    
        public virtual sanpham sanpham { get; set; }
        public virtual thanhvien thanhvien { get; set; }
    }
}
