//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbanhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaithanhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loaithanhvien()
        {
            this.thanhviens = new HashSet<thanhvien>();
        }
    
        public int MaLoaiTV { get; set; }
        public string TenLoaiTV { get; set; }
        public string UuDai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thanhvien> thanhviens { get; set; }
    }
}
