//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbanhang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLbanhangEntities : DbContext
    {
        public QLbanhangEntities()
            : base("name=QLbanhangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<CT_DonDH> CT_DonDH { get; set; }
        public virtual DbSet<CT_phieunhap> CT_phieunhap { get; set; }
        public virtual DbSet<dondathang> dondathangs { get; set; }
        public virtual DbSet<Khachhang> Khachhangs { get; set; }
        public virtual DbSet<loaisanpham> loaisanphams { get; set; }
        public virtual DbSet<loaithanhvien> loaithanhviens { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhaSX> NhaSXes { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<thanhvien> thanhviens { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ThanhVien_Role> ThanhVien_Role { get; set; }
    }
}
